import { SkillType } from "../types/skills";
import type { ClassSpecificSkill } from "../types/skills";
import { StatusEffectType } from "../types/status";
import { BaseClass } from "../types/jobs";

const SKILLS: Record<string, ClassSpecificSkill> = {
  "Provoke": {
    reqLevel: 5,
    mpCost: 0,
    castTime: 0,
    cooldown: 15,
    duration: 1,
    description: "Provoke target to attack you",
    skillType: SkillType.PROVOKE,
  },
  "Brewer (Passive)": {
    reqLevel: 12,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "12% more potion effectiveness",
    skillType: SkillType.PASSIVE,
  },
  Lunge: {
    reqLevel: 15,
    mpCost: 25,
    castTime: 0,
    cooldown: 30,
    duration: 120,
    description: "Increased attack speed with melee weapons",
    skillType: SkillType.BUFF,
  },
  "Empower (Passive)": {
    reqLevel: 18,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase attack power of melee weapons",
    skillType: SkillType.PASSIVE,
  },
  "Leg Sweep": {
    reqLevel: 20,
    mpCost: 21,
    castTime: 0,
    cooldown: 10,
    duration: 5,
    description: "Attack and reduce target's movement speed",
    skillType: SkillType.DAMAGE_PHYSICAL,
    onHitEffects: [{ type: StatusEffectType.SLOW, duration: 5 }],
  },
  "Obscene Gesture": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 15,
    duration: 10,
    description: "Provoke target to attack you",
    skillType: SkillType.PROVOKE,
  },
  "Jousting (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Can use skills and charge on horseback",
    skillType: SkillType.PASSIVE,
  },
  Invigorate: {
    reqLevel: 5,
    mpCost: 16,
    castTime: 0,
    cooldown: 10,
    duration: 180,
    description: "Increase movement speed",
    skillType: SkillType.BUFF,
  },
  Hide: {
    reqLevel: 18,
    mpCost: 24,
    castTime: 0,
    cooldown: 3,
    duration: 0,
    description: "Stationary invisibility (2MP per second)",
    skillType: SkillType.UTILITY,
    buffEffectTable: { invisible: { stationaryOnly: true, mpCostPerSec: 2 } },
  },
  "Hawkeye (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase accuracy",
    skillType: SkillType.PASSIVE,
  },
  "Shifty (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Dodge rate buff",
    skillType: SkillType.PASSIVE,
  },
  Cloak: {
    reqLevel: 20,
    mpCost: 45,
    castTime: 2,
    cooldown: 20,
    duration: 0,
    description: "Mobile invisibility (3MP per second)",
    skillType: SkillType.UTILITY,
    buffEffectTable: { invisible: { stationaryOnly: false, mpCostPerSec: 3 } },
  },
  "Third Eye": {
    reqLevel: 28,
    mpCost: 48,
    castTime: 0.5,
    cooldown: 1.5,
    duration: 480,
    description: "Accuracy buff",
    skillType: SkillType.BUFF,
  },
  "Meditation (Passive)": {
    reqLevel: 5,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase MP regen",
    skillType: SkillType.PASSIVE,
  },
  "Fire Bolt": {
    reqLevel: 1,
    mpCost: 28,
    castTime: 0.8,
    cooldown: 2,
    duration: 0,
    description: "Fire a bolt of fire at target",
    skillType: SkillType.DAMAGE_MAGICAL,
  },
  Shock: {
    reqLevel: 12,
    mpCost: 44,
    castTime: 0.5,
    cooldown: 20,
    duration: 0,
    description: "Trip the target with electricity",
    skillType: SkillType.DAMAGE_MAGICAL,
    onHitEffects: [{ type: StatusEffectType.KNOCKDOWN }],
  },
  "Scholar (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increased magical damage",
    skillType: SkillType.PASSIVE,
  },
  "Shadow Garments (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description:
      "Fire, Ice, and Lightning resistance increase when gear is enhanced with dark",
    skillType: SkillType.PASSIVE,
  },
  "Inspiration (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase SPI based on Prayer proficiency",
    skillType: SkillType.PASSIVE,
  },
  "Blessed Garments (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description:
      "Poison, Charm, and Magic resistance increase when gear is enhanced with holy",
    skillType: SkillType.PASSIVE,
  },
  Accelerate: {
    reqLevel: 28,
    mpCost: 16,
    castTime: 0.5,
    cooldown: 1.5,
    duration: 480,
    description: "Increase movement speed of target",
    skillType: SkillType.BUFF,
  },
  "War Cry": {
    reqLevel: 28,
    mpCost: 35,
    castTime: 0.5,
    cooldown: 1.5,
    duration: 480,
    description: "Increase attack power of all allies",
    skillType: SkillType.BUFF,
  },
  Providence: {
    reqLevel: 28,
    mpCost: 62,
    castTime: 0.5,
    cooldown: 1.5,
    duration: 480,
    description: "+25 magic resistance for yourself and party",
    skillType: SkillType.BUFF,
  },
  "Rapid Fire": {
    reqLevel: 35,
    mpCost: 45,
    castTime: 0,
    cooldown: 45,
    duration: 0,
    description: "Increase attack speed (crossbow)",
    skillType: SkillType.BUFF,
  },
  "Raging Soul": {
    reqLevel: 35,
    mpCost: 35,
    castTime: 0,
    cooldown: 60,
    duration: 30,
    description: "Increase attack power of next attack",
    skillType: SkillType.BUFF,
  },
  Heal: {
    reqLevel: 18,
    mpCost: 62,
    castTime: 2,
    cooldown: 3,
    duration: 0,
    description: "Heal target",
    skillType: SkillType.HEAL,
    healing: { type: "single" },
  },
  "Tranquil Mind": {
    reqLevel: 20,
    mpCost: 50,
    castTime: 5,
    cooldown: 20,
    duration: 120,
    description: "Increase MP regen for party",
    skillType: SkillType.BUFF,
  },
  "Divine Aid": {
    reqLevel: 28,
    mpCost: 89,
    castTime: 4,
    cooldown: 1.54,
    duration: 480,
    description: "Increase LP for party, 15% of base LP + 250",
    skillType: SkillType.HP_BUFF,
  },
  "Thunder Crash": {
    reqLevel: 28,
    mpCost: 32,
    castTime: 0,
    cooldown: 5,
    duration: 0,
    description: "AOE damage",
    skillType: SkillType.DAMAGE_MAGICAL,
    isAOE: true,
  },
  "Mana Restore": {
    reqLevel: 20,
    mpCost: 32,
    castTime: 1.5,
    cooldown: 10,
    duration: 210,
    description: "Restore MP over time",
    skillType: SkillType.MP_RESTORE,
  },
  "Speedy Gale": {
    reqLevel: 28,
    mpCost: 55,
    castTime: 0,
    cooldown: 1,
    duration: 480,
    description: "Increase dodge rate",
    isBuff: true,
    buffEffectTable: {
      statTieredValues: {
        stat: 'SPI',
        proficiencyStat: 'Exorcism',
        tiers: [
          {
            threshold: 33,
            profTiers: [
              { threshold: 8, values: { dodgeChance: 13 } },
              { threshold: 16, values: { dodgeChance: 18 } },
              { threshold: 24, values: { dodgeChance: 24 } },
              { threshold: 31, values: { dodgeChance: 30 } },
              { threshold: 39, values: { dodgeChance: 37 } },
              { threshold: 47, values: { dodgeChance: 43 } },
            ],
          },
          {
            threshold: 50,
            profTiers: [
              { threshold: 8, values: { dodgeChance: 16 } },
              { threshold: 16, values: { dodgeChance: 22 } },
              { threshold: 24, values: { dodgeChance: 28 } },
              { threshold: 31, values: { dodgeChance: 35 } },
              { threshold: 39, values: { dodgeChance: 41 } },
              { threshold: 47, values: { dodgeChance: 48 } },
            ],
          },
          {
            threshold: 67,
            profTiers: [
              { threshold: 8, values: { dodgeChance: 20 } },
              { threshold: 16, values: { dodgeChance: 26 } },
              { threshold: 24, values: { dodgeChance: 33 } },
              { threshold: 31, values: { dodgeChance: 40 } },
              { threshold: 39, values: { dodgeChance: 46 } },
              { threshold: 47, values: { dodgeChance: 53 } },
            ],
          },
          {
            threshold: 100,
            profTiers: [
              { threshold: 8, values: { dodgeChance: 24 } },
              { threshold: 16, values: { dodgeChance: 30 } },
              { threshold: 24, values: { dodgeChance: 37 } },
              { threshold: 31, values: { dodgeChance: 44 } },
              { threshold: 39, values: { dodgeChance: 51 } },
              { threshold: 47, values: { dodgeChance: 58 } },
            ],
          },
        ],
      },
    },
    skillType: SkillType.BUFF,
  },
  Revive: {
    reqLevel: 35,
    mpCost: 65,
    castTime: 5,
    cooldown: 30,
    duration: 0,
    description:
      "Revive a fallen ally, restoring them with partial HP. Consumes 3 Holy Water.",
    skillType: SkillType.REVIVE,
    consumableItem: "Holy Water",
    consumableItemQuantity: 3,
  },
  "Equine Charge": {
    reqLevel: 45,
    mpCost: 19,
    castTime: 0,
    cooldown: 9,
    duration: 0,
    description: "Charge at target with your spear",
    skillType: SkillType.DAMAGE_PHYSICAL,
  },
  Charge: {
    reqLevel: 50,
    mpCost: 41,
    castTime: 0,
    cooldown: 20,
    duration: 0,
    description: "Mounted Charge/Dash/Rush (Spear)",
    skillType: SkillType.DAMAGE_PHYSICAL,
  },
  Desperado: {
    reqLevel: 45,
    mpCost: 39,
    castTime: 0,
    cooldown: 35,
    duration: 60,
    description: "Attack Power increased, damage taken increased",
    skillType: SkillType.BUFF,
  },
  "Skill Focus": {
    reqLevel: 50,
    mpCost: 3,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Sacrifice 30% of your current HP to cut CDs by 50%",
    skillType: SkillType.UTILITY,
  },
  "Deflect (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description:
      "Automatically deflects charge damage when blocking (Shield)",
    skillType: SkillType.PASSIVE,
  },
  "Bore Brunt": {
    reqLevel: 50,
    reqPoints: [{ skillName: "Defend", points: 54 }],
    mpCost: 16,
    castTime: 4,
    cooldown: 1,
    duration: 300,
    description: "Take damage for up to three party members",
    skillType: SkillType.UTILITY,
  },
  "Strong Stance (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Can use shield to block magic",
    skillType: SkillType.PASSIVE,
  },
  "Defensive Attack (Passive)": {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Can use offensive skills while blocking",
    skillType: SkillType.PASSIVE,
  },
  "Snipers Nest": {
    reqLevel: 45,
    mpCost: 45,
    castTime: 2,
    cooldown: 5,
    duration: 0,
    description:
      "Attack Power, Accuracy, Range buff while stationary (Bow, Crossbow)",
    skillType: SkillType.BUFF,
  },
  "Kindling Arrow": {
    reqLevel: 50,
    mpCost: 41,
    castTime: 1,
    cooldown: 15,
    duration: 0,
    description: "AOE fire field (bow)",
    skillType: SkillType.FIELD_SPELL,
  },
  "Watchful Eye": {
    reqLevel: 45,
    mpCost: 44,
    castTime: 2,
    cooldown: 20,
    duration: 0,
    description: "Become stationary to see and attack invisible targets",
    skillType: SkillType.UTILITY,
  },
  "Horse Archer": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 90,
    duration: 0,
    description: "Allows you to use certain skills while mounted",
    skillType: SkillType.UTILITY,
  },
  "Arrow Fusillade (Passive)": {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "+2 range and double attack with crossbow",
    skillType: SkillType.PASSIVE,
  },
  "Furtive Steps (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "No cloaked movement penalty, minor MP regen buff",
    skillType: SkillType.PASSIVE,
  },
  Counterpunch: {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 90,
    duration: 0,
    description: "Weak counter attack with knuckles",
    skillType: SkillType.DAMAGE_PHYSICAL,
  },
  "Treachery (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Can remain cloaked while placing traps",
    skillType: SkillType.PASSIVE,
  },
  Sanctuary: {
    reqLevel: 45,
    mpCost: 87,
    castTime: 5,
    cooldown: 60,
    duration: 0,
    description: "AOE LP regen",
    skillType: SkillType.PARTY_HEAL,
    healing: { type: "party" },
  },
  "Merciful Blessing (Passive)": {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase strength of heals, First Aid is instant cast",
    skillType: SkillType.PASSIVE,
  },
  Enchantment: {
    reqLevel: 45,
    mpCost: 68,
    castTime: 0.5,
    cooldown: 1.5,
    duration: 480,
    description: "Aura power buff and magical attack power buff",
    skillType: SkillType.BUFF,
  },
  "Karmic Aura (Passive)": {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Toggle to enable AOE buffs",
    skillType: SkillType.PASSIVE,
  },
  "Sound Mind (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Reduce duration of magic debuffs",
    skillType: SkillType.PASSIVE,
  },
  "Paralyzing Bond": {
    reqLevel: 50,
    mpCost: 47,
    castTime: 0,
    cooldown: 30,
    duration: 10,
    description: "Root target in place. Both you and target are immobile",
    skillType: SkillType.DEBUFF,
    onHitEffects: [{ type: StatusEffectType.ROOT, duration: 10 }],
  },
  "Mana Swap": {
    reqLevel: 45,
    mpCost: 16,
    castTime: 2,
    cooldown: 10,
    duration: 0,
    description: "Swap MP with target",
    skillType: SkillType.UTILITY,
    manaSwap: true,
  },
  "Soul Swap": {
    reqLevel: 50,
    mpCost: 21,
    castTime: 1,
    cooldown: 10,
    duration: 0,
    description: "Swap buffs with target",
    skillType: SkillType.UTILITY,
    soulSwap: true,
  },
  Teleport: {
    reqLevel: 45,
    mpCost: 62,
    castTime: 3,
    cooldown: 15,
    duration: 0,
    description: "Teleport to target",
    skillType: SkillType.UTILITY,
  },
  Memorize: {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 60,
    duration: 480,
    description: "Cast time reduced, damage increased for next spell",
    skillType: SkillType.BUFF,
  },
  Intelleto: {
    reqLevel: 50,
    mpCost: 100,
    castTime: 1,
    cooldown: 20,
    duration: 480,
    description: "Increase INT of all allies",
    skillType: SkillType.BUFF,
    isAOE: true,
  },
  "Supreme Mind (Passive)": {
    reqLevel: 50,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "INT bonus from gear is doubled",
    skillType: SkillType.PASSIVE,
  },
  "Magical Aid": {
    reqLevel: 35,
    mpCost: 28,
    castTime: 2,
    cooldown: 60,
    duration: 480,
    description: "Increase magical damage and decrease skill cooldowns",
    skillType: SkillType.BUFF,
    isAOE: true,
    magicalAid: { mpRestorePercent: 20 },
    buffEffectTable: { magicalAid: { mpRestorePercent: 20 } },
  },
  "Discomfort (Passive)": {
    reqLevel: 20,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Increase INT based on Darkness proficiency",
    skillType: SkillType.PASSIVE,
  },
  "Dark Shield (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Reduce recoil damage from Gloom",
    skillType: SkillType.PASSIVE,
  },
  "Median Riding (Passive)": {
    reqLevel: 45,
    mpCost: 0,
    castTime: 0,
    cooldown: 0,
    duration: 0,
    description: "Gain ability to cast spells while mounted",
    skillType: SkillType.PASSIVE,
  },
};

type JobSkillOverrides = Record<string, Partial<ClassSpecificSkill>>;

const OVERRIDES: Record<number, JobSkillOverrides> = {
  1: {
    "Empower (Passive)": { reqLevel: 20 },
    "War Cry": {
      isAOE: true,
      aoeRadius: 15,
      buffEffectTable: {
        attackPowerMultiplier: 1.4,
      },
    },
  },
  14: {
    Heal: {
      healing: { type: "single", baseAmount: 0, statMultipliers: { SPI: 0.5, INT: 0.8, prof: 2.0 } },
    },
  },
  18: {
    "Mana Restore": { isBuff: true },
  },
  19: {
    "Mana Restore": {
      buffEffectTable: {
        mpRestorePerTick: {
          base: 7,
          statScale: "SPI",
          proficiencyStat: "Exorcism",
          proficiencyMultiplier: 0.18,
        },
      },
    },
  },
};

const JOB_SKILL_NAMES: Record<number, string[]> = {
  0: ["Provoke", "Brewer (Passive)", "Lunge"],
  1: ["Provoke", "Brewer (Passive)", "Lunge", "Empower (Passive)", "Leg Sweep", "War Cry", "Raging Soul"],
  2: ["Provoke", "Brewer (Passive)", "Lunge", "Empower (Passive)", "Leg Sweep", "War Cry", "Raging Soul", "Desperado", "Skill Focus"],
  3: ["Provoke", "Brewer (Passive)", "Lunge", "Empower (Passive)", "Leg Sweep", "War Cry", "Raging Soul", "Equine Charge", "Jousting (Passive)", "Charge"],
  4: ["Provoke", "Brewer (Passive)", "Lunge", "Obscene Gesture", "Providence"],
  5: ["Provoke", "Brewer (Passive)", "Lunge", "Obscene Gesture", "Providence", "Deflect (Passive)", "Jousting (Passive)", "Bore Brunt"],
  6: ["Provoke", "Brewer (Passive)", "Lunge", "Obscene Gesture", "Providence", "Strong Stance (Passive)", "Jousting (Passive)", "Defensive Attack (Passive)"],
  7: ["Invigorate", "Hide"],
  8: ["Invigorate", "Hide", "Hawkeye (Passive)", "Accelerate", "Rapid Fire"],
  9: ["Invigorate", "Hide", "Hawkeye (Passive)", "Accelerate", "Rapid Fire", "Snipers Nest", "Kindling Arrow"],
  10: ["Invigorate", "Hide", "Hawkeye (Passive)", "Accelerate", "Rapid Fire", "Watchful Eye", "Horse Archer", "Arrow Fusillade (Passive)"],
  11: ["Invigorate", "Hide", "Shifty (Passive)", "Cloak", "Third Eye"],
  12: ["Invigorate", "Hide", "Shifty (Passive)", "Cloak", "Third Eye", "Furtive Steps (Passive)", "Counterpunch"],
  13: ["Invigorate", "Hide", "Shifty (Passive)", "Cloak", "Third Eye", "Treachery (Passive)"],
  14: ["Meditation (Passive)", "Heal"],
  15: ["Meditation (Passive)", "Heal", "Inspiration (Passive)", "Tranquil Mind", "Divine Aid", "Revive"],
  16: ["Meditation (Passive)", "Heal", "Inspiration (Passive)", "Tranquil Mind", "Divine Aid", "Revive", "Sanctuary", "Merciful Blessing (Passive)"],
  17: ["Meditation (Passive)", "Heal", "Inspiration (Passive)", "Tranquil Mind", "Revive", "Enchantment", "Karmic Aura (Passive)"],
  18: ["Meditation (Passive)", "Heal", "Blessed Garments (Passive)", "Mana Restore", "Speedy Gale"],
  19: ["Meditation (Passive)", "Heal", "Blessed Garments (Passive)", "Mana Restore", "Speedy Gale", "Sound Mind (Passive)", "Paralyzing Bond"],
  20: ["Meditation (Passive)", "Heal", "Blessed Garments (Passive)", "Mana Restore", "Speedy Gale", "Mana Swap", "Soul Swap"],
  21: ["Fire Bolt", "Shock"],
  22: ["Fire Bolt", "Shock", "Scholar (Passive)", "Thunder Crash"],
  23: ["Fire Bolt", "Shock", "Scholar (Passive)", "Thunder Crash", "Magical Aid"],
  24: ["Fire Bolt", "Shock", "Scholar (Passive)", "Thunder Crash", "Teleport", "Memorize", "Intelleto", "Supreme Mind (Passive)"],
  25: ["Fire Bolt", "Shock", "Shadow Garments (Passive)"],
  26: ["Fire Bolt", "Shock", "Shadow Garments (Passive)", "Discomfort (Passive)"],
  27: ["Fire Bolt", "Shock", "Shadow Garments (Passive)", "Dark Shield (Passive)", "Median Riding (Passive)"],
};

export const CLASS_SPECIFIC_SKILLS: Record<number, Record<string, ClassSpecificSkill>> = {};
for (const [idxStr, names] of Object.entries(JOB_SKILL_NAMES)) {
  const idx = Number(idxStr);
  const overrides = OVERRIDES[idx] || {};
  const job: Record<string, ClassSpecificSkill> = {};
  for (const name of names) {
    const base = SKILLS[name];
    if (!base) continue;
    const override = overrides[name];
    if (override) {
      job[name] = { ...base, ...override } as ClassSpecificSkill;
    } else {
      job[name] = base;
    }
  }
  CLASS_SPECIFIC_SKILLS[idx] = job;
}

const BASE_CLASS_OFFSETS: Record<string, number> = {
  [BaseClass.WARRIOR]: 0,
  [BaseClass.SCOUT]: 7,
  [BaseClass.ACOLYTE]: 14,
  [BaseClass.MAGE]: 21,
};

export const JOB_TO_CLASS_SKILLS_INDEX: Record<string, number> = {
  warrior: 0,
  gladiator: 1,
  juggernaut: 2,
  dragoon: 3,
  knight: 4,
  warlord: 4,
  paladin: 5,
  scout: 7,
  archer: 8,
  sniper: 9,
  hunter: 8,
  provocateur: 11,
  assassin: 13,
  saboteur: 11,
  shadowblade: 12,
  acolyte: 14,
  priest: 15,
  cleric: 16,
  enchanter: 17,
  ascetic: 18,
  monk: 19,
  exorcist: 19,
  mage: 21,
  wizard: 22,
  warlock: 23,
  conjurer: 24,
  sorcerer: 25,
  corruptor: 26,
};

export function getClassSpecificSkillsForJob(
  jobId: string,
  baseClass: BaseClass,
): Record<string, ClassSpecificSkill> {
  const index = JOB_TO_CLASS_SKILLS_INDEX[jobId];
  if (index !== undefined && CLASS_SPECIFIC_SKILLS[index]) {
    return CLASS_SPECIFIC_SKILLS[index];
  }
  const offset = BASE_CLASS_OFFSETS[baseClass];
  if (offset !== undefined && CLASS_SPECIFIC_SKILLS[offset]) {
    return CLASS_SPECIFIC_SKILLS[offset];
  }
  return {};
}
