import type { JobId } from '../types/jobs';

export interface JobSkillEntry {
  minAdeptness: number;
  maxPotential: number;
}

export interface HotJobConfig {
  proficiencyStat: string;
  coef: number;
}

export const HOT_JOB_CONFIG: Partial<Record<JobId, HotJobConfig>> = {
  enchanter: { proficiencyStat: 'Blessing', coef: 1.9 },
  exorcist: { proficiencyStat: 'Exorcism', coef: 1.34 },
  cleric: { proficiencyStat: 'Grace', coef: 0.23 },
};

export const DESIGN_JOB_IDS: Record<number, string> = {
  0: "Warrior",
  1: "Gladiator",
  2: "Juggernaut",
  3: "Dragoon",
  4: "Knight",
  5: "Warlord",
  6: "Paladin",
  7: "Scout",
  8: "Archer",
  9: "Sniper",
  10: "Hunter",
  11: "Provocateur",
  12: "Assassin",
  13: "Saboteur",
  14: "Acolyte",
  15: "Priest",
  16: "Cleric",
  17: "Enchanter",
  18: "Ascetic",
  19: "Monk",
  20: "Exorcist",
  21: "Mage",
  22: "Wizard",
  23: "Warlock",
  24: "Conjurer",
  25: "Sorcerer",
  26: "Corruptor",
  27: "Shadowblade",
};

export const ALL_SUB_CATEGORIES = [
  "Slash",
  "Thrust",
  "Cleave",
  "Bash",
  "Defend",
  "Shot",
  "Alchemy",
  "Assassination",
  "Trap",
  "Dodge",
  "Grace",
  "Blessing",
  "Exorcism",
  "Hymn",
  "Elemental",
  "Invocation",
  "Darkness",
  "Confusion",
  "Racial",
  "Horsemanship",
] as const;

const ZERO_ENTRY: JobSkillEntry = { minAdeptness: 0, maxPotential: 0 };

export const JOB_SKILL_VALUES: Record<number, Record<string, JobSkillEntry>> = {
  0: {
    Slash: { minAdeptness: 5, maxPotential: 25 },
    Thrust: { minAdeptness: 2, maxPotential: 25 },
    Cleave: { minAdeptness: 5, maxPotential: 25 },
    Bash: { minAdeptness: 2, maxPotential: 20 },
    Defend: { minAdeptness: 4, maxPotential: 25 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  1: {
    Slash: { minAdeptness: 5, maxPotential: 55 },
    Thrust: { minAdeptness: 2, maxPotential: 45 },
    Cleave: { minAdeptness: 5, maxPotential: 55 },
    Bash: { minAdeptness: 2, maxPotential: 45 },
    Defend: { minAdeptness: 4, maxPotential: 25 },
    Shot: { minAdeptness: 1, maxPotential: 15 },
    Alchemy: { minAdeptness: 0, maxPotential: 20 },
    Assassination: { minAdeptness: 0, maxPotential: 25 },
    Trap: { minAdeptness: 0, maxPotential: 20 },
    Dodge: { minAdeptness: 0, maxPotential: 10 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  2: {
    Slash: { minAdeptness: 5, maxPotential: 90 },
    Thrust: { minAdeptness: 2, maxPotential: 90 },
    Cleave: { minAdeptness: 5, maxPotential: 90 },
    Bash: { minAdeptness: 2, maxPotential: 45 },
    Defend: { minAdeptness: 4, maxPotential: 35 },
    Shot: { minAdeptness: 1, maxPotential: 20 },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 20 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  3: {
    Slash: { minAdeptness: 5, maxPotential: 60 },
    Thrust: { minAdeptness: 2, maxPotential: 90 },
    Cleave: { minAdeptness: 5, maxPotential: 60 },
    Bash: { minAdeptness: 2, maxPotential: 30 },
    Defend: { minAdeptness: 4, maxPotential: 50 },
    Shot: { minAdeptness: 1, maxPotential: 20 },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 20 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 70 },
  },
  4: {
    Slash: { minAdeptness: 5, maxPotential: 35 },
    Thrust: { minAdeptness: 2, maxPotential: 55 },
    Cleave: { minAdeptness: 5, maxPotential: 25 },
    Bash: { minAdeptness: 2, maxPotential: 35 },
    Defend: { minAdeptness: 4, maxPotential: 55 },
    Shot: { minAdeptness: 1, maxPotential: 5 },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 15 },
    Grace: { minAdeptness: 0, maxPotential: 15 },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  5: {
    Slash: { minAdeptness: 5, maxPotential: 50 },
    Thrust: { minAdeptness: 2, maxPotential: 80 },
    Cleave: { minAdeptness: 5, maxPotential: 60 },
    Bash: { minAdeptness: 2, maxPotential: 60 },
    Defend: { minAdeptness: 4, maxPotential: 90 },
    Shot: { minAdeptness: 1, maxPotential: 20 },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 10 },
    Grace: { minAdeptness: 0, maxPotential: 15 },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 15 },
  },
  6: {
    Slash: { minAdeptness: 5, maxPotential: 80 },
    Thrust: { minAdeptness: 2, maxPotential: 55 },
    Cleave: { minAdeptness: 5, maxPotential: 25 },
    Bash: { minAdeptness: 2, maxPotential: 45 },
    Defend: { minAdeptness: 4, maxPotential: 60 },
    Shot: { minAdeptness: 1, maxPotential: 5 },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 10 },
    Grace: { minAdeptness: 0, maxPotential: 55 },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { minAdeptness: 0, maxPotential: 25 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 40 },
  },
  7: {
    Slash: { minAdeptness: 4, maxPotential: 10 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 10 },
    Shot: { minAdeptness: 5, maxPotential: 25 },
    Alchemy: { minAdeptness: 4, maxPotential: 20 },
    Assassination: { minAdeptness: 3, maxPotential: 25 },
    Trap: { minAdeptness: 0, maxPotential: 20 },
    Dodge: { minAdeptness: 3, maxPotential: 20 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  8: {
    Slash: { minAdeptness: 4, maxPotential: 30 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 10 },
    Shot: { minAdeptness: 5, maxPotential: 55 },
    Alchemy: { minAdeptness: 4, maxPotential: 20 },
    Assassination: { minAdeptness: 3, maxPotential: 30 },
    Trap: { minAdeptness: 0, maxPotential: 25 },
    Dodge: { minAdeptness: 3, maxPotential: 50 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  9: {
    Slash: { minAdeptness: 4, maxPotential: 25 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 10 },
    Shot: { minAdeptness: 5, maxPotential: 90 },
    Alchemy: { minAdeptness: 4, maxPotential: 50 },
    Assassination: { minAdeptness: 3, maxPotential: 30 },
    Trap: { minAdeptness: 0, maxPotential: 40 },
    Dodge: { minAdeptness: 3, maxPotential: 90 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { minAdeptness: 5, maxPotential: 30 },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 20 },
  },
  10: {
    Slash: { minAdeptness: 4, maxPotential: 30 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 10 },
    Shot: { minAdeptness: 5, maxPotential: 70 },
    Alchemy: { minAdeptness: 4, maxPotential: 90 },
    Assassination: { minAdeptness: 3, maxPotential: 30 },
    Trap: { minAdeptness: 0, maxPotential: 70 },
    Dodge: { minAdeptness: 3, maxPotential: 50 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 50 },
  },
  11: {
    Slash: { minAdeptness: 4, maxPotential: 30 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 20 },
    Shot: { minAdeptness: 5, maxPotential: 30 },
    Alchemy: { minAdeptness: 4, maxPotential: 25 },
    Assassination: { minAdeptness: 3, maxPotential: 55 },
    Trap: { minAdeptness: 0, maxPotential: 50 },
    Dodge: { minAdeptness: 3, maxPotential: 40 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  12: {
    Slash: { minAdeptness: 4, maxPotential: 65 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 20 },
    Shot: { minAdeptness: 5, maxPotential: 30 },
    Alchemy: { minAdeptness: 4, maxPotential: 50 },
    Assassination: { minAdeptness: 3, maxPotential: 90 },
    Trap: { minAdeptness: 0, maxPotential: 50 },
    Dodge: { minAdeptness: 3, maxPotential: 65 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 20 },
  },
  13: {
    Slash: { minAdeptness: 4, maxPotential: 45 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 0, maxPotential: 25 },
    Shot: { minAdeptness: 5, maxPotential: 45 },
    Alchemy: { minAdeptness: 4, maxPotential: 60 },
    Assassination: { minAdeptness: 3, maxPotential: 55 },
    Trap: { minAdeptness: 0, maxPotential: 90 },
    Dodge: { minAdeptness: 3, maxPotential: 55 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { minAdeptness: 0, maxPotential: 15 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  14: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 20 },
    Defend: { minAdeptness: 2, maxPotential: 20 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 5, maxPotential: 25 },
    Blessing: { minAdeptness: 5, maxPotential: 25 },
    Exorcism: { minAdeptness: 5, maxPotential: 25 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  15: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 35 },
    Defend: { minAdeptness: 2, maxPotential: 30 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 5, maxPotential: 55 },
    Blessing: { minAdeptness: 5, maxPotential: 55 },
    Exorcism: { minAdeptness: 5, maxPotential: 30 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  16: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { minAdeptness: 0, maxPotential: 15 },
    Bash: { minAdeptness: 2, maxPotential: 50 },
    Defend: { minAdeptness: 2, maxPotential: 40 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 5, maxPotential: 90 },
    Blessing: { minAdeptness: 5, maxPotential: 55 },
    Exorcism: { minAdeptness: 5, maxPotential: 40 },
    Hymn: { minAdeptness: 0, maxPotential: 45 },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { minAdeptness: 0, maxPotential: 10 },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 15 },
  },
  17: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 45 },
    Defend: { minAdeptness: 2, maxPotential: 35 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 5, maxPotential: 55 },
    Blessing: { minAdeptness: 5, maxPotential: 90 },
    Exorcism: { minAdeptness: 5, maxPotential: 30 },
    Hymn: { minAdeptness: 0, maxPotential: 65 },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { minAdeptness: 0, maxPotential: 30 },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 20 },
  },
  18: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { minAdeptness: 0, maxPotential: 15 },
    Bash: { minAdeptness: 2, maxPotential: 50 },
    Defend: { minAdeptness: 2, maxPotential: 20 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 5, maxPotential: 25 },
    Blessing: { minAdeptness: 5, maxPotential: 25 },
    Exorcism: { minAdeptness: 5, maxPotential: 55 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  19: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { minAdeptness: 0, maxPotential: 15 },
    Bash: { minAdeptness: 2, maxPotential: 90 },
    Defend: { minAdeptness: 2, maxPotential: 25 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 55 },
    Grace: { minAdeptness: 5, maxPotential: 30 },
    Blessing: { minAdeptness: 5, maxPotential: 25 },
    Exorcism: { minAdeptness: 5, maxPotential: 60 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { ...ZERO_ENTRY },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  20: {
    Slash: { ...ZERO_ENTRY },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { minAdeptness: 0, maxPotential: 15 },
    Bash: { minAdeptness: 2, maxPotential: 70 },
    Defend: { minAdeptness: 2, maxPotential: 30 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 10 },
    Grace: { minAdeptness: 5, maxPotential: 45 },
    Blessing: { minAdeptness: 5, maxPotential: 30 },
    Exorcism: { minAdeptness: 5, maxPotential: 90 },
    Hymn: { minAdeptness: 0, maxPotential: 10 },
    Elemental: { ...ZERO_ENTRY },
    Invocation: { minAdeptness: 0, maxPotential: 40 },
    Darkness: { ...ZERO_ENTRY },
    Confusion: { ...ZERO_ENTRY },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  21: {
    Slash: { minAdeptness: 2, maxPotential: 15 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 2, maxPotential: 15 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 25 },
    Invocation: { minAdeptness: 5, maxPotential: 40 },
    Darkness: { minAdeptness: 0, maxPotential: 20 },
    Confusion: { minAdeptness: 0, maxPotential: 25 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  22: {
    Slash: { minAdeptness: 2, maxPotential: 20 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 2, maxPotential: 30 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 0, maxPotential: 10 },
    Blessing: { minAdeptness: 0, maxPotential: 10 },
    Exorcism: { minAdeptness: 0, maxPotential: 20 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 55 },
    Invocation: { minAdeptness: 5, maxPotential: 50 },
    Darkness: { minAdeptness: 0, maxPotential: 20 },
    Confusion: { minAdeptness: 5, maxPotential: 30 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  23: {
    Slash: { minAdeptness: 2, maxPotential: 30 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 30 },
    Defend: { ...ZERO_ENTRY },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { minAdeptness: 0, maxPotential: 40 },
    Assassination: { ...ZERO_ENTRY },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 0, maxPotential: 25 },
    Blessing: { minAdeptness: 0, maxPotential: 10 },
    Exorcism: { minAdeptness: 0, maxPotential: 40 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 90 },
    Invocation: { minAdeptness: 5, maxPotential: 50 },
    Darkness: { minAdeptness: 0, maxPotential: 30 },
    Confusion: { minAdeptness: 5, maxPotential: 40 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  24: {
    Slash: { minAdeptness: 2, maxPotential: 25 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 30 },
    Defend: { ...ZERO_ENTRY },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { ...ZERO_ENTRY },
    Assassination: { ...ZERO_ENTRY },
    Trap: { minAdeptness: 0, maxPotential: 20 },
    Dodge: { minAdeptness: 0, maxPotential: 5 },
    Grace: { minAdeptness: 0, maxPotential: 10 },
    Blessing: { minAdeptness: 0, maxPotential: 20 },
    Exorcism: { minAdeptness: 0, maxPotential: 20 },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 60 },
    Invocation: { minAdeptness: 5, maxPotential: 90 },
    Darkness: { minAdeptness: 0, maxPotential: 40 },
    Confusion: { minAdeptness: 5, maxPotential: 50 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 10 },
  },
  25: {
    Slash: { minAdeptness: 2, maxPotential: 25 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { ...ZERO_ENTRY },
    Defend: { minAdeptness: 2, maxPotential: 15 },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { minAdeptness: 0, maxPotential: 15 },
    Assassination: { minAdeptness: 0, maxPotential: 20 },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 10 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 30 },
    Invocation: { minAdeptness: 5, maxPotential: 25 },
    Darkness: { minAdeptness: 0, maxPotential: 55 },
    Confusion: { minAdeptness: 5, maxPotential: 55 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  26: {
    Slash: { minAdeptness: 2, maxPotential: 30 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 15 },
    Defend: { ...ZERO_ENTRY },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { minAdeptness: 0, maxPotential: 45 },
    Assassination: { minAdeptness: 0, maxPotential: 20 },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 40 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 30 },
    Invocation: { minAdeptness: 5, maxPotential: 50 },
    Darkness: { minAdeptness: 0, maxPotential: 70 },
    Confusion: { minAdeptness: 5, maxPotential: 90 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { ...ZERO_ENTRY },
  },
  27: {
    Slash: { minAdeptness: 2, maxPotential: 65 },
    Thrust: { ...ZERO_ENTRY },
    Cleave: { ...ZERO_ENTRY },
    Bash: { minAdeptness: 2, maxPotential: 15 },
    Defend: { ...ZERO_ENTRY },
    Shot: { ...ZERO_ENTRY },
    Alchemy: { minAdeptness: 0, maxPotential: 15 },
    Assassination: { minAdeptness: 0, maxPotential: 30 },
    Trap: { ...ZERO_ENTRY },
    Dodge: { minAdeptness: 0, maxPotential: 25 },
    Grace: { ...ZERO_ENTRY },
    Blessing: { ...ZERO_ENTRY },
    Exorcism: { ...ZERO_ENTRY },
    Hymn: { ...ZERO_ENTRY },
    Elemental: { minAdeptness: 5, maxPotential: 30 },
    Invocation: { minAdeptness: 5, maxPotential: 25 },
    Darkness: { minAdeptness: 0, maxPotential: 90 },
    Confusion: { minAdeptness: 5, maxPotential: 55 },
    Racial: { ...ZERO_ENTRY },
    Horsemanship: { minAdeptness: 0, maxPotential: 50 },
  },
};

export function getJobSkillValues(designJobId: number): Record<string, JobSkillEntry> {
  return JOB_SKILL_VALUES[designJobId] ?? Object.fromEntries(
    ALL_SUB_CATEGORIES.map((name) => [name, { ...ZERO_ENTRY }])
  );
}

export function getMinAdeptness(designJobId: number, subCategoryName: string): number {
  return getJobSkillValues(designJobId)[subCategoryName]?.minAdeptness ?? 0;
}

export function getMaxPotential(designJobId: number, subCategoryName: string): number {
  return getJobSkillValues(designJobId)[subCategoryName]?.maxPotential ?? 0;
}

const JOB_NAME_TO_DESIGN_ID: Record<string, number> = {
  'warrior': 0,
  'gladiator': 1,
  'juggernaut': 2,
  'dragoon': 3,
  'knight': 4,
  'warlord': 5,
  'paladin': 6,
  'scout': 7,
  'archer': 8,
  'sniper': 9,
  'hunter': 10,
  'provocateur': 11,
  'assassin': 12,
  'saboteur': 13,
  'acolyte': 14,
  'priest': 15,
  'cleric': 16,
  'enchanter': 17,
  'ascetic': 18,
  'monk': 19,
  'exorcist': 20,
  'mage': 21,
  'wizard': 22,
  'warlock': 23,
  'conjurer': 24,
  'sorcerer': 25,
  'corruptor': 26,
  'shadowblade': 27,
};

export function getDesignJobId(jobId: string): number {
  return JOB_NAME_TO_DESIGN_ID[jobId] ?? 0;
}
