export const GAME_CONFIG = {
  TICK_RATE: 30,
  PLAYER_SPEED: 5.5,
  PLAYER_ROTATION_SPEED: 3,
  JUMP_FORCE: 8,
  GRAVITY: 20,
  MAX_HEALTH: 100,
  RESPAWN_TIME: 5000,
  ZONE_SIZE: 100,
  VIEW_DISTANCE: 50,
  INTERPOLATION_DELAY: 100,
  ATTACK_COOLDOWN: 1000,
  AUTO_ATTACK_BASE_COOLDOWN: 3000,
  AUTO_ATTACK_MIN_COOLDOWN: 1000,
  MANUAL_ATTACK_COOLDOWN: 2000,
  MAX_INVENTORY_SLOTS: 64,
  MAX_LEVEL: 60,
  COMBAT_LOG_SIZE: 50,
  MAX_POSITION: 500,
} as const;

export const COMBAT_CONFIG = {
  BASE_ATTACK_POWER: 10,
  BASE_DEFENSE: 5,
  BASE_ATTACK_SPEED: 1.0,
  CRITICAL_CHANCE: 0.1,
  CRITICAL_MULTIPLIER: 2.0,
  ATTACK_RANGE: 2.5,
  RANGED_ATTACK_RANGE: 15,
  MANUAL_ATTACK_RANGE: 3.5,
  MANUAL_ATTACK_CONE_ANGLE: Math.PI / 2,
  MANUAL_ATTACK_MAX_TARGETS: 5,
  MANUAL_ATTACK_FALLOFF: 0.8,
  SKILL_COOLDOWN: 3000,
  DAMAGE_REDUCTION_PER_DEFENSE: 0.02,
  MIN_DAMAGE: 1
} as const;

export const REGEN_CONFIG = {
  TICK_INTERVAL_MS: 10000,
  LP_DIVISOR: 80,
  LP_STA_DIVISOR: 6,
  MP_DIVISOR: 60,
  MP_SPI_DIVISOR: 6,
  OUT_OF_COMBAT_DELAY_MS: 7000,
  IN_COMBAT_LP_MULTIPLIER: 0.25,
  IN_COMBAT_MP_MULTIPLIER: 0.1,
} as const;

export const REST_REGEN_CONFIG = {
  HP_DIVISOR: 10,
  MP_DIVISOR: 10,
  HP_STA_DIVISOR: 1,
  MP_SPI_DIVISOR: 1,
  RAMP_TICK_0: 0.5,
  RAMP_TICK_1: 0.75,
} as const;

export const NETWORK_CONFIG = {
  HEARTBEAT_INTERVAL: 30000,
  CONNECTION_TIMEOUT: 10000,
  MAX_RECONNECT_ATTEMPTS: 5,
  RECONNECT_DELAY: 2000,
  MOVEMENT_SEND_RATE: 50
} as const;

export const PROFICIENCY_CONFIG = {
  TIER_1_RATIO: 0.33,
  TIER_1_GAIN_MIN: 0.7,
  TIER_1_GAIN_MAX: 0.8,
  TIER_2_RATIO: 0.66,
  TIER_2_GAIN: 0.04,
  TIER_3_GAIN: 0.01,
  INSTANT_CAST_MULTIPLIER: 0.5,
  CAST_TIME_THRESHOLD: 0.1,
} as const;

export const WORLD_CONFIG = {
  CHUNK_SIZE: 32,
  MAX_ENTITIES_PER_ZONE: 100,
  SPAWN_RADIUS: 10,
  DESPAWN_DISTANCE: 100
} as const;
