import { ItemDefinition, ItemType, ItemRarity, EquipmentSlot, WeaponType } from '../types/items';

export const ITEM_DATABASE: Record<string, ItemDefinition> = {
  'wooden_sword': {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { attack: 5 },
    description: 'A basic training sword.',
    maxStack: 1,
    sellPrice: 5,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.SWORD
  },
  'iron_sword': {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: ItemType.WEAPON,
    rarity: ItemRarity.UNCOMMON,
    stats: { attack: 12, criticalChance: 0.05, accuracy: 3 },
    description: 'A sturdy iron blade. +3 Accuracy.',
    maxStack: 1,
    sellPrice: 25,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.SWORD
  },
  'steel_blade': {
    id: 'steel_blade',
    name: 'Steel Blade',
    type: ItemType.WEAPON,
    rarity: ItemRarity.RARE,
    stats: { attack: 22, criticalChance: 0.1, accuracy: 7, attackSpeed: 0.05 },
    description: 'A finely crafted steel sword. +7 Accuracy, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 80,
    requiredLevel: 10,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.SWORD
  },
  'wooden_bow': {
    id: 'wooden_bow',
    name: 'Wooden Bow',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { attack: 5, attackSpeed: 0.1 },
    description: 'A simple wooden bow for ranged attacks.',
    maxStack: 1,
    sellPrice: 5,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.BOW
  },
  'hunter_crossbow': {
    id: 'hunter_crossbow',
    name: 'Hunter Crossbow',
    type: ItemType.WEAPON,
    rarity: ItemRarity.UNCOMMON,
    stats: { attack: 15, accuracy: 5 },
    description: 'A sturdy crossbow. +5 Accuracy.',
    maxStack: 1,
    sellPrice: 30,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.CROSSBOW
  },
  'rusty_dagger': {
    id: 'rusty_dagger',
    name: 'Rusty Dagger',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { attack: 4, attackSpeed: 0.15, criticalChance: 0.05 },
    description: 'A small rusty dagger.',
    maxStack: 1,
    sellPrice: 3,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.DAGGER
  },
  'leather_armor': {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: ItemType.ARMOR,
    rarity: ItemRarity.COMMON,
    stats: { defense: 5, health: 10 },
    description: 'Basic leather protection.',
    maxStack: 1,
    sellPrice: 8,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.ARMOR
  },
  'chainmail': {
    id: 'chainmail',
    name: 'Chainmail',
    type: ItemType.ARMOR,
    rarity: ItemRarity.UNCOMMON,
    stats: { defense: 12, health: 25, dodge: 2 },
    description: 'Interlocking metal rings provide good protection. +2 Dodge.',
    maxStack: 1,
    sellPrice: 35,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.ARMOR,
    soulSlots: 1
  },
  'plate_armor': {
    id: 'plate_armor',
    name: 'Plate Armor',
    type: ItemType.ARMOR,
    rarity: ItemRarity.RARE,
    stats: { defense: 22, health: 50, dodge: -2, fireResist: 5, iceResist: 5 },
    description: 'Heavy plate armor for maximum protection. +5 Fire/Ice Resist, -2 Dodge.',
    maxStack: 1,
    sellPrice: 100,
    requiredLevel: 10,
    equipmentSlot: EquipmentSlot.ARMOR,
    soulSlots: 1
  },
  'cloth_helmet': {
    id: 'cloth_helmet',
    name: 'Cloth Hood',
    type: ItemType.HELMET,
    rarity: ItemRarity.COMMON,
    stats: { defense: 2, mana: 10 },
    description: 'A simple cloth hood.',
    maxStack: 1,
    sellPrice: 4,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.HELMET
  },
  'iron_helmet': {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    type: ItemType.HELMET,
    rarity: ItemRarity.UNCOMMON,
    stats: { defense: 8, lightningResist: 5 },
    description: 'A solid iron helmet. +5 Lightning Resist.',
    maxStack: 1,
    sellPrice: 20,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.HELMET
  },
  'leather_boots': {
    id: 'leather_boots',
    name: 'Leather Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.COMMON,
    stats: { defense: 3, speed: 0.05 },
    description: 'Comfortable leather boots. +5% Movement Speed.',
    maxStack: 1,
    sellPrice: 5,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'swift_boots': {
    id: 'swift_boots',
    name: 'Swift Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.RARE,
    stats: { defense: 5, speed: 0.10, dodge: 5, attackSpeed: 0.05 },
    description: 'Enchanted boots that increase movement speed. +10% Movement Speed, +5 Dodge, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 60,
    requiredLevel: 8,
    equipmentSlot: EquipmentSlot.BOOTS
  },
  'copper_ring': {
    id: 'copper_ring',
    name: 'Copper Ring',
    type: ItemType.RING,
    rarity: ItemRarity.COMMON,
    stats: { health: 5, mana: 5 },
    description: 'A simple copper ring.',
    maxStack: 1,
    sellPrice: 10,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.RING_1,
    soulSlots: 3
  },
  'flame_amulet': {
    id: 'flame_amulet',
    name: 'Flame Amulet',
    type: ItemType.NECKLACE,
    rarity: ItemRarity.RARE,
    stats: { INT: 3, fireResist: 15 },
    description: 'An amulet imbued with fire energy. +15 Fire Resist, +3 INT.',
    maxStack: 1,
    sellPrice: 75,
    requiredLevel: 8,
    equipmentSlot: EquipmentSlot.NECKLACE
  },
  'mana_belt': {
    id: 'mana_belt',
    name: 'Mana Belt',
    type: ItemType.BELT,
    rarity: ItemRarity.RARE,
    stats: { INT: 1, mana: 100 },
    description: 'A magician\'s best friend. +1 INT, MP +100.',
    maxStack: 1,
    sellPrice: 75,
    requiredLevel: 8,
    equipmentSlot: EquipmentSlot.BELT
  },
  'shadow_cloak': {
    id: 'shadow_cloak',
    name: 'Shadow Cloak',
    type: ItemType.ARMOR,
    rarity: ItemRarity.EPIC,
    stats: { defense: 15, dodge: 8, darkResist: 20, DEX: 4 },
    description: 'A cloak woven from shadow threads. +8 Dodge, +20 Dark Resist, +4 DEX.',
    maxStack: 1,
    sellPrice: 200,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.ARMOR,
    soulSlots: 2
  },
  'frost_blade': {
    id: 'frost_blade',
    name: 'Frost Blade',
    type: ItemType.WEAPON,
    rarity: ItemRarity.EPIC,
    stats: { attack: 30, criticalChance: 0.12, accuracy: 10, iceResist: 10, attackSpeed: 0.08 },
    description: 'A blade chilled by eternal frost. +10 Accuracy, +10 Ice Resist, +8% Atk Speed.',
    maxStack: 1,
    sellPrice: 250,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.WEAPON,
    soulSlots: 2,
    weaponType: WeaponType.SWORD
  },
  'basic_staff': {
    id: 'basic_staff',
    name: 'Basic Staff',
    type: ItemType.WEAPON,
    rarity: ItemRarity.COMMON,
    stats: { magicAttack: 0.05, INT: 6, DEX: 3, SPI: 4 },
    description: 'A basic staff. +5% MATK.',
    maxStack: 1,
    sellPrice: 250,
    requiredLevel: 1,
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponType: WeaponType.STAFF
  },
  'thunder_helm': {
    id: 'thunder_helm',
    name: 'Thunder Helm',
    type: ItemType.HELMET,
    rarity: ItemRarity.EPIC,
    stats: { defense: 14, STA: 3, lightningResist: 20, poisonResist: 10 },
    description: 'A helm crackling with static energy. +20 Lightning Resist, +10 Poison Resist, +3 STA.',
    maxStack: 1,
    sellPrice: 180,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.HELMET,
    soulSlots: 2
  },
  'plague_walkers': {
    id: 'plague_walkers',
    name: 'Plague Walkers',
    type: ItemType.BOOTS,
    rarity: ItemRarity.EPIC,
    stats: { defense: 10, speed: 0.15, AGI: 3, poisonResist: 20, dodge: 4 },
    description: 'Boots that resist all toxins. +15% Movement Speed, +20 Poison Resist, +4 Dodge, +3 AGI.',
    maxStack: 1,
    sellPrice: 160,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.BOOTS,
    soulSlots: 2
  },
  'windstrider_boots': {
    id: 'windstrider_boots',
    name: 'Windstrider Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 12, speed: 0.20, AGI: 5, dodge: 6, attackSpeed: 0.05 },
    description: 'Boots enchanted with wind spirits. +20% Movement Speed, +6 Dodge, +5 AGI, +5% Atk Speed.',
    maxStack: 1,
    sellPrice: 400,
    requiredLevel: 20,
    equipmentSlot: EquipmentSlot.BOOTS,
    soulSlots: 3
  },
  'dragonscale_ring': {
    id: 'dragonscale_ring',
    name: 'Dragonscale Ring',
    type: ItemType.RING,
    rarity: ItemRarity.LEGENDARY,
    stats: { health: 30, mana: 20, fireResist: 25, iceResist: 25, lightningResist: 25, darkResist: 25, poisonResist: 25 },
    description: 'A ring forged from dragon scales. +25 All Resistances.',
    maxStack: 1,
    sellPrice: 500,
    requiredLevel: 20,
    equipmentSlot: EquipmentSlot.RING_1,
    soulSlots: 3
  },
  'health_potion': {
    id: 'health_potion',
    name: 'Health Potion',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    stats: { health: 50 },
    description: 'Restores 50 health points.',
    maxStack: 20,
    sellPrice: 5,
    requiredLevel: 1
  },
  'mana_potion': {
    id: 'mana_potion',
    name: 'Mana Potion',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    stats: { mana: 40 },
    description: 'Restores 40 mana points.',
    maxStack: 20,
    sellPrice: 5,
    requiredLevel: 1
  },
  'wolf_pelt': {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'The pelt of a dire wolf. Can be sold or used in crafting.',
    maxStack: 50,
    sellPrice: 3,
    requiredLevel: 0
  },
  'goblin_ear': {
    id: 'goblin_ear',
    name: 'Goblin Ear',
    type: ItemType.QUEST,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'Proof of defeating a goblin.',
    maxStack: 50,
    sellPrice: 1,
    requiredLevel: 0
  },
  'ancient_scroll': {
    id: 'ancient_scroll',
    name: 'Ancient Scroll',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A mysterious scroll with ancient writings.',
    maxStack: 50,
    sellPrice: 10,
    requiredLevel: 0
  },
  'fire_gem': {
    id: 'fire_gem',
    name: 'Fire Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem radiating intense heat. Used in fire enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'ice_gem': {
    id: 'ice_gem',
    name: 'Ice Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem cold to the touch. Used in ice enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'lightning_gem': {
    id: 'lightning_gem',
    name: 'Lightning Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem crackling with static. Used in lightning enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'holy_gem': {
    id: 'holy_gem',
    name: 'Holy Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem glowing with divine light. Used in holy enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'dark_gem': {
    id: 'dark_gem',
    name: 'Dark Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem swallowed by shadow. Used in dark enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'poison_gem': {
    id: 'poison_gem',
    name: 'Poison Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A gem seeping venomous mist. Used in poison enchantments.',
    maxStack: 50,
    sellPrice: 15,
    requiredLevel: 0
  },
  'fire_magic_gem': {
    id: 'fire_magic_gem',
    name: 'Fire Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem radiating arcane heat. Boosts fire spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'ice_magic_gem': {
    id: 'ice_magic_gem',
    name: 'Ice Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem pulsing with frost magic. Boosts ice spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'lightning_magic_gem': {
    id: 'lightning_magic_gem',
    name: 'Lightning Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem crackling with storm magic. Boosts lightning spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'holy_magic_gem': {
    id: 'holy_magic_gem',
    name: 'Holy Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem gleaming with divine magic. Boosts holy spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'dark_magic_gem': {
    id: 'dark_magic_gem',
    name: 'Dark Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem swirling with shadow magic. Boosts dark spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'poison_magic_gem': {
    id: 'poison_magic_gem',
    name: 'Poison Magic Gem',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A gem dripping with venom magic. Boosts poison spell damage when imbued.',
    maxStack: 50,
    sellPrice: 30,
    requiredLevel: 0
  },
  'rod_of_origin': {
    id: 'rod_of_origin',
    name: 'Rod of Origin',
    type: ItemType.WEAPON,
    rarity: ItemRarity.LEGENDARY,
    stats: { magicAttack: 0.15, INT: 10, SPI: 8, DEX: 5, accuracy: 8 },
    description: 'A rod of immense arcane power. +15% MATK, +10 INT, +8 SPI, +5 DEX, +8 Accuracy.',
    maxStack: 1,
    sellPrice: 1000,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.WEAPON,
    soulSlots: 3,
    weaponType: WeaponType.WAND
  },
  'eternal_torso': {
    id: 'eternal_torso',
    name: 'Eternal Torso',
    type: ItemType.ARMOR,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 30, magicAttack: 0.05, health: 80, SPI: 5 },
    description: 'Armor forged from eternal flame. +5% MATK, +30 Defense, +80 HP, +5 SPI.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.ARMOR,
    soulSlots: 3
  },
  'example_gloves': {
    id: 'example_gloves',
    name: 'Swift Gloves',
    type: ItemType.GLOVES,
    rarity: ItemRarity.UNCOMMON,
    stats: { defense: 3, castSpeed: 0.03 },
    description: 'Light gloves that quicken the hands. +3% Cast Speed.',
    maxStack: 1,
    sellPrice: 20,
    requiredLevel: 5,
    equipmentSlot: EquipmentSlot.GLOVES
  },
  'eternal_gloves': {
    id: 'eternal_gloves',
    name: 'Eternal Gloves',
    type: ItemType.GLOVES,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 7, magicAttack: 0.02, speed: 0.10, health: 50, INT: 2, castSpeed: 0.03 },
    description: 'Gloves forged from eternal flame. +5% MATK, +10% Speed, +3% Cast Speed, +20 Defense, +50 HP, +4 INT.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.GLOVES,
    soulSlots: 3
  },
  'eternal_legs': {
    id: 'eternal_legs',
    name: 'Eternal Legs',
    type: ItemType.LEGS,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 20, magicAttack: 0.05, speed: 0.10, health: 50, INT: 4 },
    description: 'Leggings forged from eternal flame. +5% MATK, +10% Speed, +20 Defense, +50 HP, +4 INT.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.LEGS,
    soulSlots: 3
  },
  'eternal_boots': {
    id: 'eternal_boots',
    name: 'Eternal Boots',
    type: ItemType.BOOTS,
    rarity: ItemRarity.LEGENDARY,
    stats: { defense: 20, magicAttack: 0.05, speed: 0.10, health: 50, INT: 4 },
    description: 'Boots forged from eternal flame. +5% MATK, +10% Speed, +20 Defense, +50 HP, +4 INT.',
    maxStack: 1,
    sellPrice: 800,
    requiredLevel: 25,
    equipmentSlot: EquipmentSlot.BOOTS,
    soulSlots: 3
  },
  'earring_of_power': {
    id: 'earring_of_power',
    name: 'Earring of Power',
    type: ItemType.EARRING,
    rarity: ItemRarity.EPIC,
    stats: { magicAttack: 0.03, INT: 3, mana: 30 },
    description: 'A glowing earring that amplifies magic. +3% MATK, +3 INT, +30 MP.',
    maxStack: 1,
    sellPrice: 300,
    requiredLevel: 15,
    equipmentSlot: EquipmentSlot.EARRING_1,
    soulSlots: 2
  },
  'trap': {
    id: 'trap',
    name: 'Trap',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'A mechanical trap used by Trap skills. Consumed on use.',
    maxStack: 99,
    sellPrice: 5,
    requiredLevel: 1,
  },
  'container': {
    id: 'container',
    name: 'Glass Container',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'An empty glass container used for crafting potions and holy water.',
    maxStack: 99,
    sellPrice: 2,
    requiredLevel: 1,
  },
  'deadly_nightshade': {
    id: 'deadly_nightshade',
    name: 'Deadly Nightshade',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'A poisonous herb used in Poison Making.',
    maxStack: 99,
    sellPrice: 3,
    requiredLevel: 1,
  },
  'antidote_herb': {
    id: 'antidote_herb',
    name: 'Antidote Herb',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'A cleansing herb used to create antidotes.',
    maxStack: 99,
    sellPrice: 3,
    requiredLevel: 1,
  },
  'moonlight_herb': {
    id: 'moonlight_herb',
    name: 'Moonlight Herb',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'A luminous herb used in potion crafting.',
    maxStack: 99,
    sellPrice: 3,
    requiredLevel: 1,
  },
  'aquilegia': {
    id: 'aquilegia',
    name: 'Aquilegia',
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    stats: {},
    description: 'A rare herb used in potion crafting.',
    maxStack: 99,
    sellPrice: 3,
    requiredLevel: 1,
  },
  'holy_water': {
    id: 'holy_water',
    name: 'Holy Water',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'Blessed water used in sacred rituals. Consumed by Sacrifice.',
    maxStack: 99,
    sellPrice: 10,
    requiredLevel: 1,
  },
  'poison_vial': {
    id: 'poison_vial',
    name: 'Poison Vial',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'A vial of deadly poison. Used by assassination skills.',
    maxStack: 99,
    sellPrice: 8,
    requiredLevel: 1,
  },
  'antidote': {
    id: 'antidote',
    name: 'Antidote',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.UNCOMMON,
    stats: {},
    description: 'Cures poison and disease.',
    maxStack: 99,
    sellPrice: 10,
    requiredLevel: 1,
  },
  'mysterious_potion': {
    id: 'mysterious_potion',
    name: 'Mysterious Potion',
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.RARE,
    stats: {},
    description: 'A strange potion that cures disease, silence, and burn.',
    maxStack: 99,
    sellPrice: 25,
    requiredLevel: 1,
  },
};

export function getItem(id: string): ItemDefinition | undefined {
  return ITEM_DATABASE[id];
}
